### ISSUE TITLE
parser.add_argument

### ISSUE THREAD

**Issue by milkdudnipples** [joaomatosf/jexboss#13]
I'm executing in the correct syntax: 

`python jexboss.py -host https://host`

I keep getting this returned:

`parser.add_argument('-mode', help="Operation mode", choices={'standalone','auto-scan', 'file-scan'}, default='standalone')`

What am I doing wrong?  Thanks!

**Comment by joaomatosf** [comment]
Hello Friend,

  This error is occurring because you are using the 2.6 version of python. The jexboss requires version >= 2.7.
   To solve the problem, you can install python 2.7 by following the steps below:


# yum -y install centos-release-scl
# yum -y install python27
# scl enable python27 bash
# pip install -r requires.txt

OBS: Note that I realized an update on requires.txt file. Before you run the last command, obtain the latest version of jexboss.

Any problem I am available.

Thanks for the feedback.

**Comment by milkdudnipples** [comment]
Thanks so much! (I figured it was something silly)
