### ISSUE TITLE
Auto Eploit not working correctly?

### ISSUE THREAD

**Issue by mdegrazia** [joaomatosf/jexboss#15]
I noticed that the variable was declared as "auto-exploit", but was referenced as "auto_exploit" in the rest of the code (dash vs. underscore). This may be causing issues with the intended function of auto-exploit feature:

Line 505: parser.add_argument("--auto-exploit", "-A",....

Line 228:  if not gl_args.auto_exploit:

**Comment by joaomatosf** [comment]
Hello Mari,

Thank you for feeback.

The use of underscode should not cause problems, since this is the behavior expected by argparser.
According to the documentation, any character "-" is replaced by "_".

You can confirm by checking the item "16.4.3.11 dest." In the official documentation, available at this link:
https://docs.python.org/3/library/argparse.html

`ny internal - characters will be converted to _ characters to make sure the string is a valid attribute name. The examples below illustrate this behavior:`


Best regards
