### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by kayhankayihan** [joaomatosf/jexboss#2]
Hello,

I have a problem, failed script.

* Checking Host: http://x.x.x.x:9443/ **

 * Checking web-console: 	 [ VULNERABLE ]
 * Checking jmx-console: 	 [ VULNERABLE ]
 * Checking JMXInvokerServlet: 	 [ VULNERABLE ]

 * Do you want to try to run an automated exploitation via "jmx-console" ?
   This operation will provide a simple command shell to execute commands on the server..
   Continue only if you have permission!
   yes/NO ? yes

 * Sending exploit code to http://x.x.x.x:9443/. Wait...

 * Successfully deployed code! Starting command shell, wait...

 * - - - - - - - - - - - - - - - - - - - - LOL - - - - - - - - - - - - - - - - - - - - * 

 * http://x.x.x.x:9443/: 

Traceback (most recent call last):
  File "jexboss.py", line 415, in <module>
    autoExploit(url, i)
  File "jexboss.py", line 105, in autoExploit
    shell_http(url, type)
  File "jexboss.py", line 133, in shell_http
    resp += " " + r.data.split(">")[1]
IndexError: list index out of range

**Comment by joaomatosf** [comment]
Hello Friend,

First sorry for the long delay in answering it.

By the output that you have shown, there is apparently an IPS blocking sending commands after exploitation (the exploitation was successful, indicating that most likely the host is vulnerable).

If you wish, you can send me the IP address so that I can look into this particular case and perform the update tool.

I soon be releasing an update that will better address cases of IPS bypass. I am preparing a model that allows performing an exchange os symmetric key and thus encrypt the payload containing commands.

Best regards.

**Comment by joaomatosf** [comment]
Hello Friends,
This problem must be resolved with the latest version that was released.
Please upgrade and try again.

Best regards
