### ISSUE TITLE
Detection of CVE-2010-1871

### ISSUE THREAD

**Issue by jonbullock** [joaomatosf/jexboss#32]
I'd like to add support for the detection of this vulnerability, would you be interested if I submitted a pull request for this?

**Comment by joaomatosf** [comment]
Hi Jonathan,
I really appreciate your initiative to improve the tool. But right now, I already have a set of various exploits (including CVE-2010-1871, various struts and some deserialization bugs for which there are no public exploits yet) ready to be released. I have not yet added to the tool because I'm doing code refactoring (and waiting for some vendors to apply bug fixes), just to make it easier to add new features / exploits / detectors.
As soon as I complete the refactoring, I'll let you know.
Again, thank you very much.

**Comment by jonbullock** [comment]
OK looking forward to seeing the update 👍
