### ISSUE TITLE
shell doesn't work on windows systems

### ISSUE THREAD

**Issue by fdiskyou** [joaomatosf/jexboss#6]
Not sure it it is a bug or a feature, but if you try to exploit a vulnerability in a Windows target the Shell doesn't work. All the vulnerabilities are correctly identified though.

**Comment by joaomatosf** [comment]
Hello Friend,
You're always getting the message "Unknown command."? You can test if the command "whoami" is working?

**Comment by fdiskyou** [comment]
whoami is actually working, but I couldn't find any other command that actually works.

**Comment by joaomatosf** [comment]
Ok, I could identify the problem. I will correct right now. Thanks for the feedback.

**Comment by fdiskyou** [comment]
Awesome. Thanks. Let me know if you need further testing.

**Comment by joaomatosf** [comment]
This is happening because the line in the shell to identify the system is windows is fault (if (System.getProperty ("os.name"). ToLowerCase (). IndexOf ("win")> 0)).
Probably the system is answering a string in Chinese.
In a one hour I will release the patch. For now, you can use the following form in your browser:
http://YOUR_PC:PORT/jexws/jexws.jsp?ppp=cmd.exe / C dir
Replace all spaces with %20. Example: http://YOUR_PC:PORT/jexws/jexws.jsp?ppp=cmd.exe%20/%20C%20dir

**Comment by joaomatosf** [comment]
Hello Friend,
The problem has been fixed. You could check if it will work on your server?

Thanks,

**Comment by fdiskyou** [comment]
Yes, it works now.
Thanks.

**Comment by joaomatosf** [comment]
Great. Thanks again for the feedback and the test.
Best regards
